# Generated by Django 5.1.5 on 2025-01-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("release_date", models.DateField()),
                ("rating", models.FloatField()),
                ("platforms", models.CharField(max_length=500)),
                (
                    "background_image",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("genres", models.CharField(blank=True, max_length=500, null=True)),
                ("developer", models.CharField(blank=True, max_length=200, null=True)),
                ("publisher", models.CharField(blank=True, max_length=200, null=True)),
                ("website", models.URLField(blank=True, max_length=500, null=True)),
                ("screenshots", models.TextField(blank=True, null=True)),
                ("videos", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
