# Generated by Django 5.1.5 on 2025-01-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameboxd", "0003_clip_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="suggestions_count",
        ),
        migrations.AddField(
            model_name="game",
            name="added_by_status",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
