# Generated by Django 5.1.5 on 2025-01-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameboxd", "0004_remove_game_suggestions_count_game_added_by_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="slug",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
