# Generated by Django 5.1.6 on 2025-02-27 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameboxd", "0005_game_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("max_requests", models.IntegerField()),
                ("results_per_page", models.IntegerField()),
                ("metacritic", models.CharField(default="60,100", max_length=20)),
                ("ordering", models.CharField(default="-rating", max_length=50)),
                ("genres", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(default="En cours", max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name="game",
            name="description",
        ),
        migrations.AddField(
            model_name="game",
            name="developers",
            field=models.ManyToManyField(related_name="games", to="gameboxd.developer"),
        ),
        migrations.AddField(
            model_name="game",
            name="genres",
            field=models.ManyToManyField(related_name="games", to="gameboxd.genre"),
        ),
        migrations.AddField(
            model_name="game",
            name="platforms",
            field=models.ManyToManyField(related_name="games", to="gameboxd.platform"),
        ),
        migrations.AddField(
            model_name="game",
            name="publishers",
            field=models.ManyToManyField(related_name="games", to="gameboxd.publisher"),
        ),
        migrations.AlterField(
            model_name="developer",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="genre",
            name="slug",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="platform",
            name="slug",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("game", "title")},
        ),
        migrations.AlterUniqueTogether(
            name="screenshot",
            unique_together={("game", "image")},
        ),
        migrations.DeleteModel(
            name="Clip",
        ),
    ]
