# Generated by Django 5.1.6 on 2025-02-27 12:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gameboxd", "0006_importhistory_remove_game_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importhistory",
            name="genres",
        ),
        migrations.RemoveField(
            model_name="importhistory",
            name="ordering",
        ),
    ]
