# Generated by Django 5.1.7 on 2025-03-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameboxd", "0007_remove_importhistory_genres_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importhistory",
            name="progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="importhistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="importhistory",
            name="metacritic",
            field=models.CharField(max_length=20),
        ),
    ]
