# Generated by Django 5.1.7 on 2025-04-02 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameboxd", "0009_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="developers",
        ),
        migrations.RemoveField(
            model_name="game",
            name="publishers",
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=255)),
                ("score", models.CharField(max_length=10)),
                ("content", models.TextField()),
                ("source", models.CharField(default="Metacritic", max_length=100)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gameboxd.game"
                    ),
                ),
            ],
            options={
                "unique_together": {("game", "platform", "author")},
            },
        ),
    ]
