name: Django CI (SQLite)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DEBUG: "1"
      SECRET_KEY: dummy
      DJANGO_SETTINGS_MODULE: game_portal.settings  
      GITHUB_WORKFLOW: true  

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Appliquer les migrations
      run: python manage.py migrate

    - name: Lancer les tests
      run: python manage.py test
